version: '3'
services:
  # Service for the React app
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ncc-frontend
    ports:
      - "8282:8282"  # Map your app's port to the host machine
    working_dir: /var/www/html/ncc/build/
    volumes:
      - ./build:/var/www/html/ncc/build/  # Map the built app files into the container
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    networks:
      - ncc-network

  # Service for Nginx
  nginx:
    image: nginx:latest
    container_name: ncc-nginx
    ports:
      - "80:80"  # Map port 80 of the host machine to Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Map your nginx.conf
      - ./build:/var/www/html/ncc/build/  # Map the built app files into the container
    depends_on:
      - react-app
    networks:
      - ncc-network

networks:
  ncc-network:
