export const homeConstants = {
  HOME_REQUEST: 'HOME_PAGE_REQUEST',
  DATA_SUMMARY: 'DATA_SUMMARY',
  GENOMIC_INFORMATION:"GENOMIC_INFORMATION",
  USERDATA_VISUALIZATION:"USERDATA_VISUALIZATION"
}

export const dataVisualization = {
  CIRCOS_REQUEST: 'CIRCOS_DATA_REQUEST',
  ONCO_REQUEST:'ONCO_REQUEST',
  REQUEST_DONE:'REQUEST_DONE'
}


export const userdataVisualization = {
  CIRCOS_REQUEST: 'CIRCOS_DATA_REQUEST',
  ONCO_REQUEST:'ONCO_REQUEST',
  REQUEST_DONE:'REQUEST_DONE'
}
