export const homeConstants = {
  HOME_REQUEST: 'HOME_PAGE_REQUEST',
  DATA_SUMMARY: 'DATA_SUMMARY',
  GENOMIC_INFORMATION:"GENOMIC_INFORMATION",
  USERDATA_VISUALIZATION:"USERDATA_VISUALIZATION",
  USERDATA_VISUALIZATION_ERROR: "USERDATA_VISUALIZATION_ERROR"
}

export const dataVisualization = {
  CIRCOS_REQUEST: 'CIRCOS_DATA_REQUEST',
  ONCO_REQUEST:'ONCO_REQUEST',
  KEYS_REQUEST:'KEYS_REQUEST',
  REQUEST_DONE:'REQUEST_DONE',
  LOLLIPOP_REQUEST:'LOLLIPOP_REQUEST',
  VOLCANO_REQUEST:'VOLCANO_REQUEST',
  HEATMAP_REQUEST:'HEATMAP_REQUEST',
  CIRCOS_SAMPLES_RNID: 'CIRCOS_SAMPLES_RNID',
  SURVIVAL_REQUEST:"SURVIVAL_REQUEST",
  SCATTER_REQUEST:"SCATTER_REQUEST",
  IGV_REQUEST:"IGV_REQUEST",
  FUSION_REQUEST:"FUSION_REQUEST",
  BOX_REQUEST:"BOX_REQUEST",
  ONCO_IMAGES_INFORMATION:"ONCO_IMAGES_INFORMATION",
  CIRCOS_TIMELINE_GRAPH: "CIRCOS_TIMELINE_GRAPH",
  REGISTER_REQUEST:"REGISTER_REQUEST",
  KMEAN_REQUEST:"KMEAN_REQUEST"
}


export const userdataVisualization = {
  CIRCOS_REQUEST: 'CIRCOS_DATA_REQUEST',
  ONCO_REQUEST:'ONCO_REQUEST',
  VOLCANO_REQUEST:'VOLCANO_REQUEST',
  REQUEST_DONE:'REQUEST_DONE',
  USER_DATA_PROJECT_TABLE: 'USER_DATA_PROJECT_TABLE'
}
